# Exported from Render on 2024-08-11T19:23:39Z
databases:
- name: api-corelab
  databaseName: api_corelab
  user: api_corelab_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
